# Generated by Django 4.1.5 on 2023-01-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rechargeapp', '0002_recharge_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactus',
            new_name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='no subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
