# Generated by Django 4.1.5 on 2023-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0003_rename_contactus_contact_message_contact_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
