# Generated by Django 4.1.5 on 2023-01-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0005_recharge_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
