# Generated by Django 4.1.5 on 2023-01-19 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rechargeapp', '0008_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.IntegerField()),
                ('card_on_name', models.CharField(max_length=100)),
                ('creditno', models.BigIntegerField()),
                ('expmonth', models.CharField(max_length=14)),
                ('expyear', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('integrity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
