# Generated by Django 4.1.5 on 2023-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0009_carddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='creditno',
            field=models.TextField(),
        ),
    ]
