# Generated by Django 4.1.5 on 2023-01-19 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rechargeapp', '0010_alter_carddetails_creditno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='integrity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
