# Generated by Django 4.1.5 on 2023-01-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0012_herounlimited_otherpacks_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='calls',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
