# Generated by Django 4.1.5 on 2023-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeapp', '0013_alter_recommended_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='calls',
            field=models.CharField(blank=True, default='NA', max_length=20),
        ),
    ]
